---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - apps.yml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.7.3
  - ingress.yml
  - namespace.yml
  - secrets.yml

patches:
  - path: patch-argocd-cm.yml
  - path: patch-argocd-rbac-cm.yml

