---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: argocd-keycloak-oidc
  labels:
    app.kubernetes.io/name: argocd-keycloak-oidc
    app.kubernetes.io/part-of: argocd
spec:
  path: in-cluster/infra/argocd/oidc
  keys:
    - keycloak.clientSecret
  type: Opaque
  reconcileStrategy: Merge

