apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    namespace: portfolio
    name: in-cluster
  source:
    repoURL: https://github.com/MartinBourbier/infra.git
    targetRevision: HEAD
    path: k3s/manifests/portfolio

