---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: postgres
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: postgres
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: postgres
  project: default
  source:
    repoURL: https://github.com/MartinBourbier/infra.git
    targetRevision: HEAD
    path: k3s/manifests/postgres

