---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
spec:
  source:
    helm:
      values: |
        vault:
          authMethod: kubernetes
          reconciliationTime: 60
          address: http://vault.api.martinbourbier.com:8201
        resources:
          requests:
            cpu: 50m
            memory: 128Mi

