---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: bitwarden
  labels:
    app: bitwarden
spec:
  serviceName: bitwarden
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: bitwarden
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      serviceAccountName: bitwarden
      securityContext:
        fsGroup: 33
        runAsUser: 33
      containers:
        - image: vaultwarden/server:1.29.2
          imagePullPolicy: IfNotPresent
          name: bitwarden
          envFrom:
            - configMapRef:
                name: bitwarden
          env:
            - name: PUSH_INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  name: bitwarden-push-installation-credentials
                  key: PUSH_INSTALLATION_ID
            - name: PUSH_INSTALLATION_KEY
              valueFrom:
                secretKeyRef:
                  name: bitwarden-push-installation-credentials
                  key: PUSH_INSTALLATION_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bitwarden-database-info
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 3012
              name: websocket
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: bitwarden-volume
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      volumes:
        - name: bitwarden-volume
          persistentVolumeClaim:
            claimName: bitwarden-volume

