---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - ingress.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: keycloak-db-config
    literals:
      - KC_DB=postgres
      - KC_DB_URL_HOST=main-cluster.postgres.svc.cluster.local
      - KC_HOSTNAME=https://keycloak.api.martinbourbier.com

