---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: minio-root-creds
spec:
  path: in-cluster/infra/minio
  keys:
    - MINIO_ROOT_USER
    - MINIO_ROOT_PASSWORD
    - MINIO_IDENTITY_OPENID_CLIENT_SECRET
  type: Opaque

