---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: app
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/MartinBourbier/infra.git
    targetRevision: HEAD
    path: k8s/apps
