---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-secrets-operator
subjects:
  - kind: ServiceAccount
    name: vault-secrets-operator
    namespace: vault
roleRef:
  kind: ClusterRole
  name: vault-secrets-operator
  apiGroup: rbac.authorization.k8s.io

